### ISSUE TITLE
bipbuf_offer can not work correct

### ISSUE THREAD

**Issue by liangsijian** [willemt/bipbuffer#4]
if I have a buff like below:

```
****12**
    ^
    |
    A
```

Region B is not used. 
Now, if I want to offer more than 2 bytes for example 4 bytes "3456", the `bipbuf_offer` will return 0. 
But there are enough buffer for 4bytes, it can offer region B and the result will like below:

```
345612**
^   ^
|   |
B   A
```

**Comment by seatrix** [comment]
what's the result/
